name: "Create Zendesk Ticket"

on:
  issues:
    types: ["opened", "reopened"]

jobs:

  create-issue:
    name: "Create Issue"
    uses: mParticle/mparticle-workflows/.github/workflows/issue-created-to-zendesk.yml@ci/SQDSDKS-4936
    secrets: inherit
